server:
  servlet:
    context-path: /xuyj
    encoding:
      charset: utf-8
      force: true
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.159.145:3306/student?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

todo:
  date: "2023年03月23日"
  thing: 今天是${todo.date},你好呀
